# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_SerialPlot.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1006, 347)
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 481, 271))
        self.graphicsView.setObjectName("graphicsView")
        self.comport_comboBox = QtWidgets.QComboBox(Form)
        self.comport_comboBox.setGeometry(QtCore.QRect(20, 290, 120, 22))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        self.comport_comboBox.setFont(font)
        self.comport_comboBox.setObjectName("comport_comboBox")
        self.baudrate_comboBox = QtWidgets.QComboBox(Form)
        self.baudrate_comboBox.setGeometry(QtCore.QRect(160, 290, 120, 22))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        self.baudrate_comboBox.setFont(font)
        self.baudrate_comboBox.setEditable(True)
        self.baudrate_comboBox.setObjectName("baudrate_comboBox")
        self.baudrate_comboBox.addItem("")
        self.baudrate_comboBox.addItem("")
        self.baudrate_comboBox.addItem("")
        self.baudrate_comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(410, 290, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("#pushButton{\n"
"   background: #cdcdcd;\n"
"   color: white;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_2.setGeometry(QtCore.QRect(510, 10, 481, 271))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 325, 741, 20))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.baudrate_comboBox.setItemText(0, _translate("Form", "9600 baud"))
        self.baudrate_comboBox.setItemText(1, _translate("Form", "38400 baud"))
        self.baudrate_comboBox.setItemText(2, _translate("Form", "115200 baud"))
        self.baudrate_comboBox.setItemText(3, _translate("Form", "256000 baud"))
        self.pushButton.setText(_translate("Form", "START"))
        self.label.setText(_translate("Form", "data"))
